imports:
    - { resource: parameters.yml }
    - { resource: doctrine.yml }
    - { resource: doctrine_migrations.yml }
    - { resource: framework.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fos_config.yml }
    - { resource: monolog.yml }
    - { resource: sonata.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

nelmio_api_doc: ~
