fos_rest:
    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false                           # We do not include format in request, so that all responses
    access_denied_listener:                             # will eventually be JSON formated
        json: true

fos_user:
    db_driver: orm
    firewall_name: api                                  # Seems to be used when registering user/reseting password,
                                                        # but since there is no "login", as so it seems to be useless in
                                                        # our particular context, but still required by "FOSUserBundle"
    user_class: AuthenticationBundle\Entity\User

    service:
        mailer: fos_user.mailer.noop

    from_email:
        address: "yourapp@yourapp.com"
        sender_name: "Demo String"

fos_oauth_server:
    db_driver:           orm
    client_class:        AuthenticationBundle\Entity\Client
    access_token_class:  AuthenticationBundle\Entity\AccessToken
    refresh_token_class: AuthenticationBundle\Entity\RefreshToken
    auth_code_class:     AuthenticationBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username           # This property will be used when valid credentials are given to load the user upon access token creation