monolog:
    handlers:
        rest_log:
            type: stream
            # log to app/logs/(environment).log
            path: "%kernel.logs_dir%/rest.log"

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error