rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /rest/doc

app_area:
   resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
   prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/all.xml"