rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /rest/doc