PaymentBundle\Entity\Customer:
    type: entity
    repositoryClass: PaymentBundle\Persistent\CustomerRepository
    table: pay_customers
    uniqueConstraints:
        customer_id_uindex:
            columns:
                - id
        customer_cnp_uindex:
            columns:
                - cnp
        customer_name_cnp_uindex:
            columns:
                - name
                - cnp
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        cnp:
            type: string
            nullable: false
            length: 13
            options:
                fixed: false
    lifecycleCallbacks: {  }
