services:
    # ...
    admin.category:
        class: \AppBundle\Admin\TransactionsAdmin
        arguments: [~, PaymentBundle\Entity\Transaction, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Transactions }
        public: true